sudo: required

language: c

services:
- docker

before_install:
- docker build -t zhuikov/predator-prey .

script:
- docker run -v /home/travis/build/Zhuikov/predator-prey/sources/:/sources zhuikov/predator-prey /bin/bash -c "cd /sources/Predator-prey; qmake; make; cp /sources/Predator-prey/CLI/CLI /usr/bin/pp-model"
- docker run -v /home/travis/build/Zhuikov/predator-prey/sources/:/sources zhuikov/predator-prey /sources/Predator-prey/tests/tst_modeltest
- docker run zhuikov/predator-prey /opt/anaconda/bin/conda run "jupyter nbconvert --to notebook --execute ModelLaunchExample.ipynb"
- docker run zhuikov/predator-prey /opt/anaconda/bin/conda run "jupyter nbconvert --to notebook --execute LifeModel.ipynb"

notifications:
  email:
    - k.vilegzhanina@gmail.com
    - artem.zhuikov@mail.ru
    - vadik.dyachkov@gmail.com
    - yurij.lezhenin@yandex.ru
    - n.v.bogach@gmail.com
