sudo: required

language: c

services:
- docker

before_install:
- docker build -t zhuikov/predator-prey .

script:
- docker run -v /home/travis/build/Zhuikov/predator-prey/sources/:/sources zhuikov/predator-prey /bin/bash -c "cd /sources/Predator-prey; qmake; make"
- docker run -v /home/travis/build/Zhuikov/predator-prey/sources/:/sources zhuikov/predator-prey /sources/Predator-prey/tests/tst_modeltest
- travis_wait 50 mvn install
- docker run -v /home/travis/build/Zhuikov/predator-prey/:/repo zhuikov/predator-prey /bin/bash /repo/notebooks/nbconv.sh

notifications:
  email:
    - k.vilegzhanina@gmail.com
    - artem.zhuikov@mail.ru
    - vadik.dyachkov@gmail.com
    - yurij.lezhenin@yandex.ru
    - n.v.bogach@gmail.com
